# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bc56687c364f3f38b502ce7ac0aaaa704e9471e898c2a56dc1852b92704ae89da82aea5130c92cae4483e98a2f1aa4cf844006dadd7bdfb95555dac39deca3a

test:
  secret_key_base: 5bf29a4ca048c63879b990849d0ff91cff823e905b3b75be76c117e3ce0c999c4f0065253124c98b2d275245e2625c5897e2df0fbd7c2531c828556befffc8ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
